function runDownloadBatch(){return lockRun_('downloads',()=>{
  const s=sheet_(SH.SHEETS.QUEUE,SH.QUEUE_HEADERS),all=rows_(s),batch=all.filter(x=>['DISCOVERED','VALIDATED','DOWNLOAD_PENDING','DOWNLOAD_FAILED'].includes(String(x.status).toUpperCase())).slice(0,Math.max(1,Math.min(50,Number(props_().getProperty('DL_BATCH_SIZE')||10))));
  let downloaded=0,failed=0;
  batch.forEach(row=>{try{downloadPair_(row);setQueue_(s,row._row,{status:'DOWNLOADED',notes:'Paper and memo saved successfully'});downloaded++;}catch(err){setQueue_(s,row._row,{status:'DOWNLOAD_FAILED',notes:String(err).slice(0,500)});failed++;log_('DOWNLOAD_FAILED',row.paper_url,row,'','ERROR',String(err));}});
  props_().setProperty('DL_LAST_RUN',new Date().toISOString());
  return {processed:batch.length,downloaded,failed,pending:Math.max(0,all.length-batch.length)};
});}
function downloadPair_(r){const rootId=props_().getProperty('SOURCE_LIBRARY_ID');if(!rootId)throw new Error('Missing SOURCE_LIBRARY_ID Script Property');const root=DriveApp.getFolderById(rootId);const folder=pathFolder_(root,[String(r.year),'Grade_'+r.grade,safe_(r.subject),safe_(r.assessment_type),safe_(r.language),safe_(r.paper_type)]);const p=fetchBinary_(r.paper_url,r.paper_file_type),m=fetchBinary_(r.memo_url,r.memo_file_type);saveUnique_(folder,p,'Paper_'+safeFile_(nameFromUrl_(r.paper_url),r.paper_file_type));saveUnique_(folder,m,'Memo_'+safeFile_(nameFromUrl_(r.memo_url),r.memo_file_type));setQueue_(sheet_(SH.SHEETS.QUEUE,SH.QUEUE_HEADERS),r._row,{source_folder_url:folder.getUrl()});log_('DOWNLOAD_SUCCESS',r.source_url,{paper:r.paper_url,memo:r.memo_url},folder.getUrl(),'OK','');}
function fetchBinary_(url,expected){let last='';for(let n=1;n<=3;n++){try{const res=UrlFetchApp.fetch(String(url),{muteHttpExceptions:true,followRedirects:true,headers:{'User-Agent':'StudyHub/1.0'}});if(res.getResponseCode()<200||res.getResponseCode()>299)throw new Error('HTTP '+res.getResponseCode());const b=res.getBlob(),bytes=b.getBytes();if(expected==='PDF'&&!(bytes[0]===37&&bytes[1]===80&&bytes[2]===68&&bytes[3]===70))throw new Error('Not a PDF signature');if(expected==='ZIP'&&!(bytes[0]===80&&bytes[1]===75))throw new Error('Not a ZIP signature');return b;}catch(e){last=String(e);Utilities.sleep(n*1000);}}throw new Error('Download failed after 3 attempts: '+last);}
function pathFolder_(root,parts){let f=root;parts.forEach(n=>{const it=f.getFoldersByName(n);f=it.hasNext()?it.next():f.createFolder(n);});return f;}
function saveUnique_(folder,blob,name){const old=folder.getFilesByName(name);if(old.hasNext())return old.next();blob.setName(name);return folder.createFile(blob);}
function setQueue_(s,row,changes){const h=s.getRange(1,1,1,s.getLastColumn()).getValues()[0].map(String);Object.keys(changes).forEach(k=>{const i=h.indexOf(k);if(i>=0)s.getRange(row,i+1).setValue(changes[k]);});}
function safe_(v){return String(v||'Unknown').replace(/[\\/:*?"<>|]/g,'-').trim();}
function nameFromUrl_(u){try{return decodeURIComponent(String(u).split('/').pop().split('?')[0]);}catch(_){return 'file';}}
function safeFile_(name,type){let n=safe_(name);const ext=type==='ZIP'?'.zip':'.pdf';if(!n.toLowerCase().endsWith(ext))n+=ext;return n;}
